volumes:
  pg_data_production:
  static_volume:


services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sashalesik/taski_backend
    volumes:
      - static_volume:/backend_static
  frontend:
    image: sashalesik/taski_frontend  # Качаем с Docker Hub
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: sashalesik/taski_gateway  # Качаем с Docker Hub
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80