# docker-compose.production.yml
volumes:
  pg_data_production:
  static:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sashalesik/taski_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/backend_static/static
  frontend:
    image: sashalesik/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/  # Копируем собранные файлы в папку, которую видит gateway
    volumes:
      - static:/frontend_static

  gateway:
    depends_on:
      - backend
    image: sashalesik/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80