volumes:
  pg_data_production:
  static_volume:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: sashalesik/taski_backend
    volumes:
      - static_volume:/backend_static
  frontend:
    image: sashalesik/taski_frontend  # Качаем с Docker Hub
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: sashalesik/taski_gateway  # Качаем с Docker Hub
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80